[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

# Original Foundry Setup:

# [profile.default]
# src = "src"
# out = "out"
# libs = ["lib"]
# optimizer = true
# optimizer_runs = 20000